litthe cosmetic changes in endpoint_context.py
Fixed: tests/test_24_authorization_endpoint.py
Sometimes test_inputs fails for input elements order

I get in tests/test_26_userinfo_endpoint.py
ImportError: No module named 'oidcendpoint.oidc.add_on.custom_scopes'
and yes, it's missing. Is it still to be committed?

Then test_30_end_session.py: got many failures.
Fixed three of them regarding url-args ordering but cookie with "wrong client" error
and another KeyError still have to be patched.

	modified:   README.md
	modified:   src/oidcendpoint/endpoint_context.py
	modified:   tests/test_24_authorization_endpoint.py
	modified:   tests/test_30_end_session.py
	requirements-dev.txt