"AttributeError: 'dict' object has no attribute 'startswith'" in oidcendpoint/endpoint.py(158)client_authentication() because using gunicorn webserver request is {}
patched, need revision

	modified:   src/oidcendpoint/client_authn.py